theme: jekyll-theme-minimal
author:
  name     : "Jocelyn Ong"
  avatar   : "/images/profile.jpg"
  bio      : ""
  location : "Singapore"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jocelyn-ong-wj/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/joce_ong"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jocelyn-ong"
    - label: "Email"
      icon: "fab fa-fw fa-instagram"
      url: "https://mailto:ongjoce@gmail.com"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      author_profile: true
      read_time: # true
      comments: # true
      share: # true
      related: # true